# Generated by Django 3.2.11 on 2022-03-07 18:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viajepage',
            name='location',
        ),
        migrations.AddField(
            model_name='viajepage',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='viajepage',
            name='latitud',
            field=models.CharField(max_length=250, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='viajepage',
            name='longitud',
            field=models.CharField(max_length=250, null=True, verbose_name='longitud'),
        ),
        migrations.CreateModel(
            name='NoticiasPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='viajes.viajepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
