# Generated by Django 3.2.11 on 2022-03-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
