# Generated by Django 3.2.11 on 2022-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0002_delete_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, verbose_name='Ranking')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='título')),
                ('rating', models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='Puntuacion')),
                ('imagen', models.URLField(blank=True, max_length=250)),
                ('link', models.URLField()),
                ('episodes', models.CharField(blank=True, max_length=250, verbose_name='Episodios')),
                ('emmision', models.CharField(blank=True, max_length=250, verbose_name='Emision')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
    ]
