# Generated by Django 3.2.11 on 2022-03-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_animeindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Puntuacion'),
        ),
    ]
